posite_name: sbersupermarket-product-scraper
nav:
  - Get started: docs/index.md
theme:
  name: 'readthedocs'
markdown_extensions:
  - admonition
  - codehilite

repo_name: 'sbersupermarket-product-scraper'
repo_url: 'https://github.com/chaotism/sbersupermarket-product-scraper'
