version: "3"
services:
  api:
    build:
      context: ../
      dockerfile: ./docker/application/Dockerfile
    command: poetry run python3 start_server.py
    environment:
      API_HOST: "0.0.0.0"
      API_PORT: "8888"
      POSTGRES_DB: "srv_marketplaces"
      POSTGRES_USER: "srv_marketplaces"
      POSTGRES_PASSWORD: "look_in_vault"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      SBER_PARSER_POOL_SIZE: 2
      SBER_PARSER_POOL_FASTLOAD: "TRUE"
      SBER_MEGAMARKET_URI: "https://sbermegamarket.ru"
    env_file:
      - ../.env
    ports:
      - "8888:8888"
    shm_size: "2gb"
    mem_reservation: "2gb"
    restart: always
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: "srv_marketplaces"
      POSTGRES_USER: "srv_marketplaces"
      POSTGRES_PASSWORD: "look_in_vault"
    ports:
      - "5432:5432"
